#ifndef UTILS_H
#define UTILS_H
#include <vector>
#include <map>
#include <ostream>
#include <unordered_map>

#include "utils/templateUtils.cpp"

//low-level functions (**oblivious** to SANA or network alignment) but that are useful in multiple places.

//folder where any part of the codebase can save autogenerated files
extern const std::string AUTOGENEREATED_FILES_FOLDER;
namespace sana {
    typedef uint16_t ushort;
    typedef uint32_t uint;
}
typedef uint16_t ushort;
typedef uint32_t uint;

bool myNan(double x);

double randDouble();
int randInt(int low, int high);
int randMod(int n);
void randomShuffle(std::vector<uint>& v);

std::string extractDecimals(double value, int count);
std::string toLowerCase(const std::string& s);
std::vector<std::string> nonEmptySplit(const std::string& s, char c); //keeps only non-empty strings

double vectorMean(const std::vector<double>& v);
void normalizeWeights(std::vector<double>& weights);

void printTable(const std::vector<std::vector<std::string>>& table, int colSeparation, std::ostream& stream);

std::string currentDateTime();

std::string exec(std::string cmd);
std::string execWithoutPrintingErr(std::string cmd);
void execPrintOutput(std::string cmd);

#endif /* UTILS_H */
